// =====================================================
// ARI REBIRTH
// File: js/training/exercises/strength/legs.js
// Version: 1.0.0
// Purpose:
//   Lower-body strength and hypertrophy exercise data
//   for the ARI Training Exercise Registry.
//
// Design:
//   - Preserves existing lower-body exercise IDs used by plans.
//   - Covers squat, split-squat, lunge, leg-press,
//     knee-extension, hamstring-curl, hinge, and step patterns.
//   - Keeps glute-isolation and calf-isolation exercises in
//     their own future modules to avoid duplicate exercise IDs.
//   - Uses existing anatomy and movement-pattern IDs.
//   - Adds aliases, target emphasis, substitution groups,
//     substitutions, laterality, setup, and logging metadata.
// =====================================================

const VERSION = "1.0.0";
const SOURCE = "js/training/exercises/strength/legs";

const LEG_EXERCISES = Object.freeze([
  {
    id: "barbell_back_squat",
    name: "Barbell Back Squat",
    aliases: ["back squat", "barbell squat", "high bar squat", "low bar squat"],
    category: "strength",
    exerciseTypes: ["strength", "hypertrophy", "free_weight"],
    bodyParts: ["lower_body", "quadriceps", "glutes", "hamstrings", "core"],
    primaryMuscles: ["rectus_femoris", "vastus_lateralis", "vastus_medialis", "gluteus_maximus"],
    secondaryMuscles: ["biceps_femoris", "erector_spinae", "adductor_magnus"],
    movementPatterns: ["squat"],
    equipment: ["barbell", "squat_rack"],
    difficulty: "intermediate",
    targetEmphasis: { muscle: "rectus_femoris", region: "compound_lower_body", label: "Quads + Glutes" },
    substitutionGroup: "bilateral_squat",
    substitutions: ["barbell_front_squat", "hack_squat", "leg_press", "smith_machine_squat", "goblet_squat"],
    laterality: "bilateral",
    setup: "squat_rack",
    goals: { muscle_building: 10, strength: 10, lower_body_strength: 10, athletic_performance: 8, general_fitness: 7 },
    summary: "Squat down with a bar supported across the upper back, then stand by extending the hips and knees.",
    instructions: ["Set the bar securely across the upper back.", "Brace the torso and begin the descent through the hips and knees.", "Lower to a controlled depth that preserves stable positioning.", "Drive through the feet to stand."],
    cues: ["Keep the knees tracking in line with the feet.", "Maintain a controlled trunk position."],
    logging: { type: "sets_reps_weight", fields: ["sets", "reps", "weight", "rest_seconds"] },
    illustration: { anatomy: null, movement: null }
  },
  {
    id: "barbell_front_squat",
    name: "Barbell Front Squat",
    aliases: ["front squat", "barbell front squat", "front rack squat"],
    category: "strength",
    exerciseTypes: ["strength", "hypertrophy", "free_weight"],
    bodyParts: ["lower_body", "quadriceps", "glutes", "core"],
    primaryMuscles: ["rectus_femoris", "vastus_lateralis", "vastus_medialis", "vastus_intermedius"],
    secondaryMuscles: ["gluteus_maximus", "erector_spinae", "adductor_magnus"],
    movementPatterns: ["squat"],
    equipment: ["barbell", "squat_rack"],
    difficulty: "advanced",
    targetEmphasis: { muscle: "rectus_femoris", region: "quadriceps", label: "Quads" },
    substitutionGroup: "bilateral_squat",
    substitutions: ["barbell_back_squat", "hack_squat", "goblet_squat", "leg_press"],
    laterality: "bilateral",
    setup: "front_rack",
    goals: { muscle_building: 9, strength: 9, lower_body_strength: 10, athletic_performance: 8 },
    summary: "Squat with the bar supported across the front of the shoulders to emphasize the quadriceps and upright torso control.",
    instructions: ["Set the bar in a stable front-rack position.", "Brace the torso and keep the elbows elevated.", "Descend through the hips and knees.", "Drive through the feet to stand."],
    cues: ["Keep the chest tall.", "Do not allow the elbows to collapse downward."],
    logging: { type: "sets_reps_weight", fields: ["sets", "reps", "weight", "rest_seconds"] },
    illustration: { anatomy: null, movement: null }
  },
  {
    id: "goblet_squat",
    name: "Goblet Squat",
    aliases: ["dumbbell goblet squat", "kettlebell goblet squat", "goblet squats"],
    category: "strength",
    exerciseTypes: ["strength", "hypertrophy", "free_weight"],
    bodyParts: ["lower_body", "quadriceps", "glutes", "core"],
    primaryMuscles: ["rectus_femoris", "vastus_lateralis", "vastus_medialis", "gluteus_maximus"],
    secondaryMuscles: ["biceps_femoris", "erector_spinae"],
    movementPatterns: ["squat"],
    equipment: ["dumbbell", "kettlebell"],
    difficulty: "beginner",
    targetEmphasis: { muscle: "rectus_femoris", region: "compound_lower_body", label: "Quads + Glutes" },
    substitutionGroup: "bilateral_squat",
    substitutions: ["barbell_back_squat", "barbell_front_squat", "hack_squat", "leg_press"],
    laterality: "bilateral",
    setup: "standing",
    goals: { muscle_building: 8, strength: 7, lower_body_strength: 8, general_fitness: 9 },
    summary: "Hold a weight at the chest, squat down under control, and stand by extending the hips and knees.",
    instructions: ["Hold a dumbbell or kettlebell close to the chest.", "Sit down between the hips while bending the knees.", "Maintain a stable torso.", "Stand back up through the feet."],
    cues: ["Keep the weight close to the body.", "Let the knees track with the toes."],
    logging: { type: "sets_reps_weight", fields: ["sets", "reps", "weight", "rest_seconds"] },
    illustration: { anatomy: null, movement: null }
  },
  {
    id: "hack_squat",
    name: "Hack Squat",
    aliases: ["hack squat machine", "machine hack squat", "sled hack squat"],
    category: "strength",
    exerciseTypes: ["strength", "hypertrophy", "machine_strength"],
    bodyParts: ["lower_body", "quadriceps", "glutes"],
    primaryMuscles: ["rectus_femoris", "vastus_lateralis", "vastus_medialis", "vastus_intermedius"],
    secondaryMuscles: ["gluteus_maximus", "adductor_magnus"],
    movementPatterns: ["squat"],
    equipment: ["hack_squat_machine"],
    difficulty: "beginner",
    targetEmphasis: { muscle: "rectus_femoris", region: "quadriceps", label: "Quads" },
    substitutionGroup: "bilateral_squat",
    substitutions: ["leg_press", "barbell_front_squat", "smith_machine_squat", "pendulum_squat"],
    laterality: "bilateral",
    setup: "machine",
    goals: { muscle_building: 10, strength: 8, lower_body_strength: 9 },
    summary: "Squat on a guided hack-squat machine to train the quadriceps and glutes with strong torso support.",
    instructions: ["Place the shoulders and back securely against the pads.", "Set the feet on the platform.", "Lower the sled under control.", "Press through the feet to return."],
    cues: ["Keep the knees tracking with the toes.", "Use a depth that maintains stable hip and back contact."],
    logging: { type: "sets_reps_weight", fields: ["sets", "reps", "weight", "rest_seconds"] },
    illustration: { anatomy: null, movement: null }
  },
  {
    id: "pendulum_squat",
    name: "Pendulum Squat",
    aliases: ["pendulum squat machine", "pendulum machine squat"],
    category: "strength",
    exerciseTypes: ["strength", "hypertrophy", "machine_strength"],
    bodyParts: ["lower_body", "quadriceps", "glutes"],
    primaryMuscles: ["rectus_femoris", "vastus_lateralis", "vastus_medialis", "vastus_intermedius"],
    secondaryMuscles: ["gluteus_maximus", "adductor_magnus"],
    movementPatterns: ["squat"],
    equipment: ["pendulum_squat_machine"],
    difficulty: "beginner",
    targetEmphasis: { muscle: "rectus_femoris", region: "quadriceps", label: "Quads" },
    substitutionGroup: "bilateral_squat",
    substitutions: ["hack_squat", "leg_press", "smith_machine_squat"],
    laterality: "bilateral",
    setup: "machine",
    goals: { muscle_building: 10, strength: 8, lower_body_strength: 9 },
    summary: "Squat through the arc of a pendulum machine to load the quadriceps and glutes through a supported range.",
    instructions: ["Position the shoulders securely beneath the pads.", "Place the feet firmly on the platform.", "Descend under control.", "Drive through the platform to return."],
    cues: ["Keep the knees aligned with the feet.", "Do not bounce from the bottom."],
    logging: { type: "sets_reps_weight", fields: ["sets", "reps", "weight", "rest_seconds"] },
    illustration: { anatomy: null, movement: null }
  },
  {
    id: "smith_machine_squat",
    name: "Smith Machine Squat",
    aliases: ["smith squat", "smith machine back squat", "smith squats"],
    category: "strength",
    exerciseTypes: ["strength", "hypertrophy", "machine_strength"],
    bodyParts: ["lower_body", "quadriceps", "glutes", "hamstrings"],
    primaryMuscles: ["rectus_femoris", "vastus_lateralis", "vastus_medialis", "gluteus_maximus"],
    secondaryMuscles: ["biceps_femoris", "adductor_magnus"],
    movementPatterns: ["squat"],
    equipment: ["smith_machine"],
    difficulty: "beginner",
    targetEmphasis: { muscle: "rectus_femoris", region: "compound_lower_body", label: "Quads + Glutes" },
    substitutionGroup: "bilateral_squat",
    substitutions: ["barbell_back_squat", "hack_squat", "leg_press"],
    laterality: "bilateral",
    setup: "smith_machine",
    goals: { muscle_building: 10, strength: 8, lower_body_strength: 9 },
    summary: "Squat under a Smith-machine bar using the fixed bar path for a stable lower-body strength movement.",
    instructions: ["Set the bar across the upper back.", "Position the feet to match the machine path.", "Lower through the hips and knees.", "Stand and rotate the bar into the hooks when finished."],
    cues: ["Choose foot placement that allows stable knee and hip tracking.", "Do not force an unnatural bar path."],
    logging: { type: "sets_reps_weight", fields: ["sets", "reps", "weight", "rest_seconds"] },
    illustration: { anatomy: null, movement: null }
  },
  {
    id: "leg_press",
    name: "Leg Press",
    aliases: ["leg press machine", "sled leg press", "45 degree leg press"],
    category: "strength",
    exerciseTypes: ["strength", "hypertrophy", "machine_strength"],
    bodyParts: ["lower_body", "quadriceps", "glutes", "hamstrings"],
    primaryMuscles: ["rectus_femoris", "vastus_lateralis", "vastus_medialis", "gluteus_maximus"],
    secondaryMuscles: ["biceps_femoris", "adductor_magnus"],
    movementPatterns: ["squat"],
    equipment: ["leg_press_machine"],
    difficulty: "beginner",
    targetEmphasis: { muscle: "rectus_femoris", region: "compound_lower_body", label: "Quads + Glutes" },
    substitutionGroup: "bilateral_squat",
    substitutions: ["hack_squat", "barbell_back_squat", "smith_machine_squat", "pendulum_squat"],
    laterality: "bilateral",
    setup: "machine",
    goals: { muscle_building: 10, strength: 8, lower_body_strength: 9 },
    summary: "Lower the sled by bending the hips and knees, then press it away by extending the legs.",
    instructions: ["Place the feet securely on the platform.", "Release the safety mechanism as appropriate for the machine.", "Lower the platform under control.", "Press through the feet to extend the hips and knees."],
    cues: ["Keep the hips supported against the pad.", "Do not force excessive depth."],
    logging: { type: "sets_reps_weight", fields: ["sets", "reps", "weight", "rest_seconds"] },
    illustration: { anatomy: null, movement: null }
  },
  {
    id: "single_leg_press",
    name: "Single-Leg Press",
    aliases: ["one leg press", "unilateral leg press", "single leg leg press"],
    category: "strength",
    exerciseTypes: ["strength", "hypertrophy", "machine_strength"],
    bodyParts: ["lower_body", "quadriceps", "glutes", "hamstrings"],
    primaryMuscles: ["rectus_femoris", "vastus_lateralis", "vastus_medialis", "gluteus_maximus"],
    secondaryMuscles: ["biceps_femoris", "gluteus_medius"],
    movementPatterns: ["squat"],
    equipment: ["leg_press_machine"],
    difficulty: "intermediate",
    targetEmphasis: { muscle: "rectus_femoris", region: "unilateral_lower_body", label: "Quads + Glutes" },
    substitutionGroup: "unilateral_leg_press",
    substitutions: ["bulgarian_split_squat", "reverse_lunge", "step_up"],
    laterality: "unilateral",
    setup: "machine",
    goals: { muscle_building: 9, strength: 8, lower_body_strength: 9 },
    summary: "Press the leg-press sled using one leg at a time to train unilateral lower-body strength.",
    instructions: ["Place one foot securely on the platform.", "Keep the hips level and supported.", "Lower the sled under control.", "Press through the working foot."],
    cues: ["Do not let the pelvis rotate.", "Use a load appropriate for one leg."],
    logging: { type: "sets_reps_weight", fields: ["sets", "reps", "weight", "side", "rest_seconds"] },
    illustration: { anatomy: null, movement: null }
  },
  {
    id: "bulgarian_split_squat",
    name: "Bulgarian Split Squat",
    aliases: ["bulgarian squat", "rear foot elevated split squat", "rfess", "bulgarian lunges"],
    category: "strength",
    exerciseTypes: ["strength", "hypertrophy", "free_weight"],
    bodyParts: ["lower_body", "quadriceps", "glutes", "hamstrings", "core"],
    primaryMuscles: ["rectus_femoris", "vastus_lateralis", "vastus_medialis", "gluteus_maximus"],
    secondaryMuscles: ["biceps_femoris", "gluteus_medius", "adductor_magnus"],
    movementPatterns: ["lunge"],
    equipment: ["bodyweight", "dumbbells", "barbell", "bench"],
    difficulty: "intermediate",
    targetEmphasis: { muscle: "rectus_femoris", region: "unilateral_lower_body", label: "Quads + Glutes" },
    substitutionGroup: "split_squat_lunge",
    substitutions: ["reverse_lunge", "walking_lunge", "split_squat", "single_leg_press"],
    laterality: "unilateral",
    setup: "rear_foot_elevated",
    goals: { muscle_building: 10, strength: 9, lower_body_strength: 10, athletic_performance: 9, general_fitness: 8 },
    summary: "Perform a split squat with the rear foot elevated to strongly train the working leg.",
    instructions: ["Place the rear foot on a stable bench or platform.", "Set the front foot far enough forward for stable balance.", "Lower the back knee toward the floor.", "Drive through the front foot to stand."],
    cues: ["Keep most of the load on the front leg.", "Keep the front knee tracking with the foot."],
    logging: { type: "sets_reps_weight", fields: ["sets", "reps", "weight", "side", "rest_seconds"] },
    illustration: { anatomy: null, movement: null }
  },
  {
    id: "split_squat",
    name: "Split Squat",
    aliases: ["stationary lunge", "static lunge", "split stance squat"],
    category: "strength",
    exerciseTypes: ["strength", "hypertrophy", "functional"],
    bodyParts: ["lower_body", "quadriceps", "glutes", "hamstrings", "core"],
    primaryMuscles: ["rectus_femoris", "vastus_lateralis", "vastus_medialis", "gluteus_maximus"],
    secondaryMuscles: ["biceps_femoris", "gluteus_medius"],
    movementPatterns: ["lunge"],
    equipment: ["bodyweight", "dumbbells", "barbell"],
    difficulty: "beginner",
    targetEmphasis: { muscle: "rectus_femoris", region: "unilateral_lower_body", label: "Quads + Glutes" },
    substitutionGroup: "split_squat_lunge",
    substitutions: ["bulgarian_split_squat", "reverse_lunge", "walking_lunge"],
    laterality: "unilateral",
    setup: "split_stance",
    goals: { muscle_building: 9, strength: 8, lower_body_strength: 9, general_fitness: 8 },
    summary: "Lower and raise the body from a stationary split stance to train one leg at a time.",
    instructions: ["Take a stable split stance.", "Lower the back knee toward the floor.", "Keep the front foot planted.", "Drive through the front leg to return."],
    cues: ["Maintain balance.", "Keep the front knee aligned with the toes."],
    logging: { type: "sets_reps_weight", fields: ["sets", "reps", "weight", "side", "rest_seconds"] },
    illustration: { anatomy: null, movement: null }
  },
  {
    id: "walking_lunge",
    name: "Walking Lunge",
    aliases: ["walking lunges", "dumbbell walking lunge", "walking dumbbell lunge"],
    category: "strength",
    exerciseTypes: ["strength", "hypertrophy", "functional"],
    bodyParts: ["lower_body", "quadriceps", "glutes", "hamstrings", "core"],
    primaryMuscles: ["gluteus_maximus", "rectus_femoris", "vastus_lateralis", "vastus_medialis"],
    secondaryMuscles: ["biceps_femoris", "gluteus_medius"],
    movementPatterns: ["lunge"],
    equipment: ["bodyweight", "dumbbells"],
    difficulty: "beginner",
    targetEmphasis: { muscle: "rectus_femoris", region: "dynamic_unilateral", label: "Quads + Glutes" },
    substitutionGroup: "split_squat_lunge",
    substitutions: ["reverse_lunge", "split_squat", "bulgarian_split_squat"],
    laterality: "alternating",
    setup: "walking",
    goals: { muscle_building: 8, strength: 7, lower_body_strength: 8, athletic_performance: 8, general_fitness: 8 },
    summary: "Step forward into alternating lunges while maintaining balance and control through each repetition.",
    instructions: ["Stand tall with space in front of you.", "Step forward and lower into a lunge.", "Push through the front foot to move into the next step.", "Alternate legs."],
    cues: ["Keep the front knee tracking with the foot.", "Maintain a controlled torso."],
    logging: { type: "sets_reps_weight", fields: ["sets", "reps", "weight", "distance", "rest_seconds"] },
    illustration: { anatomy: null, movement: null }
  },
  {
    id: "reverse_lunge",
    name: "Reverse Lunge",
    aliases: ["backward lunge", "rear lunge", "reverse dumbbell lunge"],
    category: "strength",
    exerciseTypes: ["strength", "hypertrophy", "functional"],
    bodyParts: ["lower_body", "quadriceps", "glutes", "hamstrings", "core"],
    primaryMuscles: ["gluteus_maximus", "rectus_femoris", "vastus_lateralis", "vastus_medialis"],
    secondaryMuscles: ["biceps_femoris", "gluteus_medius"],
    movementPatterns: ["lunge"],
    equipment: ["bodyweight", "dumbbells", "barbell"],
    difficulty: "beginner",
    targetEmphasis: { muscle: "gluteus_maximus", region: "unilateral_lower_body", label: "Glutes + Quads" },
    substitutionGroup: "split_squat_lunge",
    substitutions: ["walking_lunge", "split_squat", "bulgarian_split_squat"],
    laterality: "alternating_or_unilateral",
    setup: "standing",
    goals: { muscle_building: 9, strength: 8, lower_body_strength: 9, athletic_performance: 8, general_fitness: 8 },
    summary: "Step backward into a lunge, then drive through the front leg to return to standing.",
    instructions: ["Stand tall.", "Step one leg backward.", "Lower the back knee toward the floor.", "Push through the front foot to return."],
    cues: ["Keep the front foot planted.", "Maintain a controlled torso."],
    logging: { type: "sets_reps_weight", fields: ["sets", "reps", "weight", "side", "rest_seconds"] },
    illustration: { anatomy: null, movement: null }
  },
  {
    id: "forward_lunge",
    name: "Forward Lunge",
    aliases: ["front lunge", "forward dumbbell lunge"],
    category: "strength",
    exerciseTypes: ["strength", "hypertrophy", "functional"],
    bodyParts: ["lower_body", "quadriceps", "glutes", "hamstrings"],
    primaryMuscles: ["rectus_femoris", "vastus_lateralis", "vastus_medialis", "gluteus_maximus"],
    secondaryMuscles: ["biceps_femoris", "gluteus_medius"],
    movementPatterns: ["lunge"],
    equipment: ["bodyweight", "dumbbells"],
    difficulty: "beginner",
    targetEmphasis: { muscle: "rectus_femoris", region: "unilateral_lower_body", label: "Quads + Glutes" },
    substitutionGroup: "split_squat_lunge",
    substitutions: ["reverse_lunge", "walking_lunge", "split_squat"],
    laterality: "alternating_or_unilateral",
    setup: "standing",
    goals: { muscle_building: 8, strength: 7, lower_body_strength: 8, general_fitness: 8 },
    summary: "Step forward into a lunge and push back to the starting position.",
    instructions: ["Stand tall.", "Step forward with one leg.", "Lower both knees under control.", "Push through the front foot to return."],
    cues: ["Use a controlled step length.", "Keep the front knee aligned with the foot."],
    logging: { type: "sets_reps_weight", fields: ["sets", "reps", "weight", "side", "rest_seconds"] },
    illustration: { anatomy: null, movement: null }
  },
  {
    id: "lateral_lunge",
    name: "Lateral Lunge",
    aliases: ["side lunge", "lateral dumbbell lunge"],
    category: "strength",
    exerciseTypes: ["strength", "functional", "mobility"],
    bodyParts: ["lower_body", "quadriceps", "glutes", "adductors", "hips"],
    primaryMuscles: ["gluteus_maximus", "adductor_magnus", "rectus_femoris"],
    secondaryMuscles: ["gluteus_medius", "vastus_lateralis", "vastus_medialis"],
    movementPatterns: ["lunge"],
    equipment: ["bodyweight", "dumbbells"],
    difficulty: "intermediate",
    targetEmphasis: { muscle: "adductor_magnus", region: "frontal_plane_lower_body", label: "Adductors + Glutes" },
    substitutionGroup: "lateral_lower_body",
    substitutions: ["cossack_squat", "split_squat"],
    laterality: "unilateral",
    setup: "standing",
    goals: { muscle_building: 7, strength: 7, lower_body_strength: 8, mobility: 7, athletic_performance: 9 },
    summary: "Step to the side and sit into one hip while keeping the opposite leg more extended.",
    instructions: ["Stand with room to move laterally.", "Step to one side.", "Bend the working knee and sit the hips back.", "Push through the working foot to return."],
    cues: ["Keep the working foot planted.", "Keep the knee tracking with the toes."],
    logging: { type: "sets_reps_weight", fields: ["sets", "reps", "weight", "side", "rest_seconds"] },
    illustration: { anatomy: null, movement: null }
  },
  {
    id: "cossack_squat",
    name: "Cossack Squat",
    aliases: ["cossack", "side to side squat", "deep lateral squat"],
    category: "strength",
    exerciseTypes: ["strength", "mobility", "functional"],
    bodyParts: ["lower_body", "quadriceps", "glutes", "adductors", "hips"],
    primaryMuscles: ["adductor_magnus", "gluteus_maximus", "rectus_femoris"],
    secondaryMuscles: ["gluteus_medius", "hamstrings"],
    movementPatterns: ["lunge"],
    equipment: ["bodyweight", "dumbbell", "kettlebell"],
    difficulty: "advanced",
    targetEmphasis: { muscle: "adductor_magnus", region: "frontal_plane_lower_body", label: "Adductors + Mobility" },
    substitutionGroup: "lateral_lower_body",
    substitutions: ["lateral_lunge"],
    laterality: "alternating",
    setup: "wide_stance",
    goals: { mobility: 10, flexibility: 8, lower_body_strength: 7, athletic_performance: 8 },
    summary: "Shift deeply from side to side in a wide stance to train lateral lower-body strength and mobility.",
    instructions: ["Take a wide stance.", "Shift the hips toward one leg.", "Bend that knee while the opposite leg remains more extended.", "Return through the center and repeat on the other side."],
    cues: ["Use only a range you can control.", "Keep the working heel planted."],
    logging: { type: "sets_reps_weight", fields: ["sets", "reps", "weight", "side", "rest_seconds"] },
    illustration: { anatomy: null, movement: null }
  },
  {
    id: "step_up",
    name: "Step-Up",
    aliases: ["step up", "box step up", "bench step up", "dumbbell step up"],
    category: "strength",
    exerciseTypes: ["strength", "functional", "free_weight"],
    bodyParts: ["lower_body", "quadriceps", "glutes", "calves"],
    primaryMuscles: ["gluteus_maximus", "rectus_femoris", "vastus_lateralis", "vastus_medialis"],
    secondaryMuscles: ["gluteus_medius", "gastrocnemius", "soleus"],
    movementPatterns: ["step"],
    equipment: ["box", "bench", "bodyweight", "dumbbells"],
    difficulty: "beginner",
    targetEmphasis: { muscle: "gluteus_maximus", region: "unilateral_lower_body", label: "Glutes + Quads" },
    substitutionGroup: "step",
    substitutions: ["bulgarian_split_squat", "reverse_lunge", "single_leg_press"],
    laterality: "unilateral",
    setup: "elevated_surface",
    goals: { strength: 7, muscle_building: 7, lower_body_strength: 8, running: 7, athletic_performance: 8, general_fitness: 8 },
    summary: "Step onto an elevated surface and drive through the working leg to bring the body upward.",
    instructions: ["Place one foot fully on a stable box or bench.", "Drive through that foot to step up.", "Stand tall on the platform.", "Lower under control."],
    cues: ["Avoid pushing excessively from the trailing leg.", "Keep the knee aligned over the foot."],
    logging: { type: "sets_reps_weight", fields: ["sets", "reps", "weight", "box_height", "side", "rest_seconds"] },
    illustration: { anatomy: null, movement: null }
  },
  {
    id: "leg_extension",
    name: "Leg Extension",
    aliases: ["leg extension machine", "quad extension", "knee extension machine"],
    category: "strength",
    exerciseTypes: ["hypertrophy", "machine_strength"],
    bodyParts: ["quadriceps", "lower_body"],
    primaryMuscles: ["rectus_femoris", "vastus_lateralis", "vastus_medialis", "vastus_intermedius"],
    secondaryMuscles: [],
    movementPatterns: ["knee_extension"],
    equipment: ["leg_extension_machine"],
    difficulty: "beginner",
    targetEmphasis: { muscle: "rectus_femoris", region: "quadriceps_isolation", label: "Quads" },
    substitutionGroup: "knee_extension",
    substitutions: ["single_leg_extension"],
    laterality: "bilateral",
    setup: "seated_machine",
    goals: { muscle_building: 10, strength: 6, lower_body_strength: 6 },
    summary: "Extend the knees against machine resistance, then return to the bent-knee position under control.",
    instructions: ["Adjust the machine so the knee aligns with the pivot.", "Place the lower legs behind the pad.", "Extend the knees.", "Lower the weight under control."],
    cues: ["Avoid using momentum.", "Keep the hips against the seat."],
    logging: { type: "sets_reps_weight", fields: ["sets", "reps", "weight", "rest_seconds"] },
    illustration: { anatomy: null, movement: null }
  },
  {
    id: "single_leg_extension",
    name: "Single-Leg Extension",
    aliases: ["one leg extension", "unilateral leg extension", "single leg quad extension"],
    category: "strength",
    exerciseTypes: ["hypertrophy", "machine_strength"],
    bodyParts: ["quadriceps", "lower_body"],
    primaryMuscles: ["rectus_femoris", "vastus_lateralis", "vastus_medialis", "vastus_intermedius"],
    secondaryMuscles: [],
    movementPatterns: ["knee_extension"],
    equipment: ["leg_extension_machine"],
    difficulty: "beginner",
    targetEmphasis: { muscle: "rectus_femoris", region: "quadriceps_isolation", label: "Quads" },
    substitutionGroup: "knee_extension",
    substitutions: ["leg_extension"],
    laterality: "unilateral",
    setup: "seated_machine",
    goals: { muscle_building: 10, strength: 6, lower_body_strength: 6 },
    summary: "Perform the leg-extension movement with one leg at a time.",
    instructions: ["Adjust the machine correctly.", "Use one leg against the pad.", "Extend the knee under control.", "Lower slowly before switching sides."],
    cues: ["Keep the hips supported.", "Match the range between sides."],
    logging: { type: "sets_reps_weight", fields: ["sets", "reps", "weight", "side", "rest_seconds"] },
    illustration: { anatomy: null, movement: null }
  },
  {
    id: "seated_leg_curl",
    name: "Seated Leg Curl",
    aliases: ["seated hamstring curl", "seated leg curl machine", "hamstring curl machine"],
    category: "strength",
    exerciseTypes: ["hypertrophy", "machine_strength"],
    bodyParts: ["hamstrings", "lower_body"],
    primaryMuscles: ["biceps_femoris", "semitendinosus", "semimembranosus"],
    secondaryMuscles: ["gastrocnemius"],
    movementPatterns: ["knee_flexion"],
    equipment: ["leg_curl_machine"],
    difficulty: "beginner",
    targetEmphasis: { muscle: "biceps_femoris", region: "hamstrings_isolation", label: "Hamstrings" },
    substitutionGroup: "hamstring_curl",
    substitutions: ["lying_leg_curl", "standing_leg_curl", "single_leg_seated_leg_curl"],
    laterality: "bilateral",
    setup: "seated_machine",
    goals: { muscle_building: 10, strength: 6, lower_body_strength: 7 },
    summary: "Bend the knees against machine resistance to bring the lower legs downward and back.",
    instructions: ["Adjust the machine to align the knees with the pivot.", "Secure the thigh pad if present.", "Flex the knees against resistance.", "Return under control."],
    cues: ["Keep the hips in contact with the seat.", "Avoid bouncing the weight."],
    logging: { type: "sets_reps_weight", fields: ["sets", "reps", "weight", "rest_seconds"] },
    illustration: { anatomy: null, movement: null }
  },
  {
    id: "lying_leg_curl",
    name: "Lying Leg Curl",
    aliases: ["lying hamstring curl", "prone leg curl", "lying leg curl machine"],
    category: "strength",
    exerciseTypes: ["hypertrophy", "machine_strength"],
    bodyParts: ["hamstrings", "lower_body"],
    primaryMuscles: ["biceps_femoris", "semitendinosus", "semimembranosus"],
    secondaryMuscles: ["gastrocnemius"],
    movementPatterns: ["knee_flexion"],
    equipment: ["lying_leg_curl_machine"],
    difficulty: "beginner",
    targetEmphasis: { muscle: "biceps_femoris", region: "hamstrings_isolation", label: "Hamstrings" },
    substitutionGroup: "hamstring_curl",
    substitutions: ["seated_leg_curl", "standing_leg_curl", "single_leg_lying_leg_curl"],
    laterality: "bilateral",
    setup: "prone_machine",
    goals: { muscle_building: 10, strength: 6, lower_body_strength: 7 },
    summary: "Flex the knees while lying prone against machine resistance to isolate the hamstrings.",
    instructions: ["Lie face-down and align the knees with the machine pivot.", "Place the pad above the heels.", "Curl the lower legs upward.", "Lower slowly."],
    cues: ["Keep the hips against the pad.", "Avoid lifting the pelvis."],
    logging: { type: "sets_reps_weight", fields: ["sets", "reps", "weight", "rest_seconds"] },
    illustration: { anatomy: null, movement: null }
  },
  {
    id: "standing_leg_curl",
    name: "Standing Leg Curl",
    aliases: ["standing hamstring curl", "single leg standing curl", "standing leg curl machine"],
    category: "strength",
    exerciseTypes: ["hypertrophy", "machine_strength"],
    bodyParts: ["hamstrings", "lower_body"],
    primaryMuscles: ["biceps_femoris", "semitendinosus", "semimembranosus"],
    secondaryMuscles: ["gastrocnemius"],
    movementPatterns: ["knee_flexion"],
    equipment: ["standing_leg_curl_machine"],
    difficulty: "beginner",
    targetEmphasis: { muscle: "biceps_femoris", region: "hamstrings_isolation", label: "Hamstrings" },
    substitutionGroup: "hamstring_curl",
    substitutions: ["seated_leg_curl", "lying_leg_curl"],
    laterality: "unilateral",
    setup: "standing_machine",
    goals: { muscle_building: 9, strength: 6, lower_body_strength: 7 },
    summary: "Curl one leg against machine resistance from a standing position.",
    instructions: ["Set the machine for the working leg.", "Hold the supports for balance.", "Flex the knee to curl the pad upward.", "Lower slowly before switching sides."],
    cues: ["Keep the hips square.", "Avoid swinging the working thigh."],
    logging: { type: "sets_reps_weight", fields: ["sets", "reps", "weight", "side", "rest_seconds"] },
    illustration: { anatomy: null, movement: null }
  },
  {
    id: "single_leg_seated_leg_curl",
    name: "Single-Leg Seated Leg Curl",
    aliases: ["one leg seated curl", "single leg hamstring curl", "unilateral seated leg curl"],
    category: "strength",
    exerciseTypes: ["hypertrophy", "machine_strength"],
    bodyParts: ["hamstrings", "lower_body"],
    primaryMuscles: ["biceps_femoris", "semitendinosus", "semimembranosus"],
    secondaryMuscles: ["gastrocnemius"],
    movementPatterns: ["knee_flexion"],
    equipment: ["leg_curl_machine"],
    difficulty: "beginner",
    targetEmphasis: { muscle: "biceps_femoris", region: "hamstrings_isolation", label: "Hamstrings" },
    substitutionGroup: "hamstring_curl",
    substitutions: ["seated_leg_curl", "standing_leg_curl"],
    laterality: "unilateral",
    setup: "seated_machine",
    goals: { muscle_building: 10, strength: 6, lower_body_strength: 7 },
    summary: "Perform the seated hamstring curl with one leg at a time.",
    instructions: ["Set the machine and thigh pad.", "Use one leg against the lower pad.", "Flex the knee.", "Return slowly and switch sides."],
    cues: ["Keep the hips supported.", "Match range and tempo between sides."],
    logging: { type: "sets_reps_weight", fields: ["sets", "reps", "weight", "side", "rest_seconds"] },
    illustration: { anatomy: null, movement: null }
  },
  {
    id: "single_leg_lying_leg_curl",
    name: "Single-Leg Lying Leg Curl",
    aliases: ["one leg lying curl", "single leg prone curl", "unilateral lying leg curl"],
    category: "strength",
    exerciseTypes: ["hypertrophy", "machine_strength"],
    bodyParts: ["hamstrings", "lower_body"],
    primaryMuscles: ["biceps_femoris", "semitendinosus", "semimembranosus"],
    secondaryMuscles: ["gastrocnemius"],
    movementPatterns: ["knee_flexion"],
    equipment: ["lying_leg_curl_machine"],
    difficulty: "beginner",
    targetEmphasis: { muscle: "biceps_femoris", region: "hamstrings_isolation", label: "Hamstrings" },
    substitutionGroup: "hamstring_curl",
    substitutions: ["lying_leg_curl", "standing_leg_curl"],
    laterality: "unilateral",
    setup: "prone_machine",
    goals: { muscle_building: 10, strength: 6, lower_body_strength: 7 },
    summary: "Perform a prone hamstring curl one leg at a time.",
    instructions: ["Lie securely on the machine.", "Use one leg against the pad.", "Curl the heel toward the glutes.", "Lower slowly before switching sides."],
    cues: ["Keep the pelvis down.", "Do not twist the hips."],
    logging: { type: "sets_reps_weight", fields: ["sets", "reps", "weight", "side", "rest_seconds"] },
    illustration: { anatomy: null, movement: null }
  },
  {
    id: "romanian_deadlift",
    name: "Romanian Deadlift",
    aliases: ["rdl", "romanian dl", "barbell rdl", "dumbbell rdl"],
    category: "strength",
    exerciseTypes: ["strength", "hypertrophy", "free_weight"],
    bodyParts: ["lower_body", "hamstrings", "glutes", "lower_back", "core"],
    primaryMuscles: ["biceps_femoris", "semitendinosus", "semimembranosus", "gluteus_maximus"],
    secondaryMuscles: ["erector_spinae", "forearm_flexors"],
    movementPatterns: ["hip_hinge"],
    equipment: ["barbell", "dumbbells"],
    difficulty: "intermediate",
    targetEmphasis: { muscle: "biceps_femoris", region: "lengthened_hamstrings", label: "Hamstrings + Glutes" },
    substitutionGroup: "hip_hinge",
    substitutions: ["dumbbell_romanian_deadlift", "single_leg_romanian_deadlift", "conventional_deadlift"],
    laterality: "bilateral",
    setup: "standing",
    goals: { muscle_building: 10, strength: 9, lower_body_strength: 10, athletic_performance: 8 },
    summary: "Push the hips backward while lowering the weight close to the legs, then extend the hips to return to standing.",
    instructions: ["Stand tall holding the weight.", "Soften the knees and push the hips backward.", "Lower until you feel a strong but controlled hamstring stretch.", "Drive the hips forward to stand."],
    cues: ["Keep the weight close to the body.", "Maintain a stable spine.", "Think hips back rather than squatting down."],
    logging: { type: "sets_reps_weight", fields: ["sets", "reps", "weight", "rest_seconds"] },
    illustration: { anatomy: null, movement: null }
  },
  {
    id: "dumbbell_romanian_deadlift",
    name: "Dumbbell Romanian Deadlift",
    aliases: ["dumbbell rdl", "db rdl", "dumbbell stiff leg deadlift"],
    category: "strength",
    exerciseTypes: ["strength", "hypertrophy", "free_weight"],
    bodyParts: ["lower_body", "hamstrings", "glutes", "lower_back"],
    primaryMuscles: ["biceps_femoris", "semitendinosus", "semimembranosus", "gluteus_maximus"],
    secondaryMuscles: ["erector_spinae", "forearm_flexors"],
    movementPatterns: ["hip_hinge"],
    equipment: ["dumbbells"],
    difficulty: "beginner",
    targetEmphasis: { muscle: "biceps_femoris", region: "lengthened_hamstrings", label: "Hamstrings + Glutes" },
    substitutionGroup: "hip_hinge",
    substitutions: ["romanian_deadlift", "single_leg_romanian_deadlift"],
    laterality: "bilateral",
    setup: "standing",
    goals: { muscle_building: 10, strength: 8, lower_body_strength: 9 },
    summary: "Perform a Romanian deadlift with dumbbells held beside or in front of the legs.",
    instructions: ["Stand tall holding the dumbbells.", "Push the hips backward with soft knees.", "Lower the weights along the legs.", "Extend the hips to stand."],
    cues: ["Keep the dumbbells close.", "Maintain tension in the hamstrings."],
    logging: { type: "sets_reps_weight", fields: ["sets", "reps", "weight", "rest_seconds"] },
    illustration: { anatomy: null, movement: null }
  },
  {
    id: "single_leg_romanian_deadlift",
    name: "Single-Leg Romanian Deadlift",
    aliases: ["single leg rdl", "one leg rdl", "single leg dumbbell deadlift"],
    category: "strength",
    exerciseTypes: ["strength", "hypertrophy", "functional", "free_weight"],
    bodyParts: ["lower_body", "hamstrings", "glutes", "core"],
    primaryMuscles: ["biceps_femoris", "semitendinosus", "semimembranosus", "gluteus_maximus"],
    secondaryMuscles: ["gluteus_medius", "erector_spinae"],
    movementPatterns: ["hip_hinge"],
    equipment: ["bodyweight", "dumbbell", "dumbbells", "kettlebell"],
    difficulty: "intermediate",
    targetEmphasis: { muscle: "biceps_femoris", region: "unilateral_posterior_chain", label: "Hamstrings + Glutes" },
    substitutionGroup: "unilateral_hip_hinge",
    substitutions: ["dumbbell_romanian_deadlift", "romanian_deadlift"],
    laterality: "unilateral",
    setup: "standing",
    goals: { muscle_building: 8, strength: 8, lower_body_strength: 9, athletic_performance: 9 },
    summary: "Hinge on one leg while the opposite leg extends behind the body, then return to standing.",
    instructions: ["Stand on one leg with a slight knee bend.", "Push the hips backward as the free leg extends behind you.", "Keep the pelvis controlled.", "Drive through the standing hip to return."],
    cues: ["Keep the hips square.", "Use support if balance limits the hamstring stimulus."],
    logging: { type: "sets_reps_weight", fields: ["sets", "reps", "weight", "side", "rest_seconds"] },
    illustration: { anatomy: null, movement: null }
  },
  {
    id: "conventional_deadlift",
    name: "Conventional Deadlift",
    aliases: ["deadlift", "barbell deadlift", "conventional dl"],
    category: "strength",
    exerciseTypes: ["strength", "free_weight"],
    bodyParts: ["full_body", "lower_body", "glutes", "hamstrings", "back", "core", "forearms"],
    primaryMuscles: ["gluteus_maximus", "biceps_femoris", "semitendinosus", "semimembranosus", "erector_spinae"],
    secondaryMuscles: ["latissimus_dorsi", "forearm_flexors", "quadriceps"],
    movementPatterns: ["hip_hinge"],
    equipment: ["barbell"],
    difficulty: "advanced",
    targetEmphasis: { muscle: "gluteus_maximus", region: "posterior_chain", label: "Posterior Chain" },
    substitutionGroup: "deadlift",
    substitutions: ["sumo_deadlift", "romanian_deadlift"],
    laterality: "bilateral",
    setup: "floor",
    goals: { strength: 10, muscle_building: 8, lower_body_strength: 10, athletic_performance: 8 },
    summary: "Lift a bar from the floor by extending the hips and knees while maintaining a controlled trunk position.",
    instructions: ["Set the feet beneath the bar.", "Grip the bar and brace the trunk.", "Drive through the floor while extending the hips and knees.", "Stand tall, then return the bar to the floor under control."],
    cues: ["Keep the bar close to the body.", "Avoid jerking the bar from the floor."],
    logging: { type: "sets_reps_weight", fields: ["sets", "reps", "weight", "rest_seconds"] },
    illustration: { anatomy: null, movement: null }
  },
  {
    id: "sumo_deadlift",
    name: "Sumo Deadlift",
    aliases: ["sumo barbell deadlift", "wide stance deadlift"],
    category: "strength",
    exerciseTypes: ["strength", "free_weight"],
    bodyParts: ["lower_body", "glutes", "hamstrings", "quadriceps", "adductors", "back", "core"],
    primaryMuscles: ["gluteus_maximus", "adductor_magnus", "rectus_femoris"],
    secondaryMuscles: ["biceps_femoris", "erector_spinae", "forearm_flexors"],
    movementPatterns: ["hip_hinge"],
    equipment: ["barbell"],
    difficulty: "advanced",
    targetEmphasis: { muscle: "adductor_magnus", region: "wide_stance_posterior_chain", label: "Glutes + Adductors" },
    substitutionGroup: "deadlift",
    substitutions: ["conventional_deadlift", "romanian_deadlift"],
    laterality: "bilateral",
    setup: "wide_stance_floor",
    goals: { strength: 10, muscle_building: 8, lower_body_strength: 10 },
    summary: "Deadlift from a wide stance with the hands inside the legs, emphasizing the hips, adductors, and lower body.",
    instructions: ["Take a wide stance with the toes turned out comfortably.", "Grip the bar inside the legs.", "Brace the torso and drive through the floor.", "Stand tall and lower the bar under control."],
    cues: ["Keep the knees tracking with the toes.", "Keep the bar close to the body."],
    logging: { type: "sets_reps_weight", fields: ["sets", "reps", "weight", "rest_seconds"] },
    illustration: { anatomy: null, movement: null }
  }
]);

export {
  VERSION,
  SOURCE,
  LEG_EXERCISES
};

export default LEG_EXERCISES;
