-- =====================================================
-- ARI EXPERIENCE
-- Seed manufacturer-verified Cheetos Flamin' Hot products.
-- Sources: PepsiCo SmartLabel / Frito-Lay.
-- =====================================================

insert into public.food_database (
  canonical_key,
  name,
  display_name,
  brand,
  category,
  subcategory,
  aliases,
  tags,
  upcs,
  serving_size,
  serving_grams,
  calories,
  protein_g,
  carbs_g,
  fat_g,
  fiber_g,
  sugar_g,
  sodium_mg,
  nutrition_basis_grams,
  source,
  source_type,
  source_id,
  source_url,
  source_payload,
  verified,
  confidence,
  popularity,
  retailer_private_label,
  active,
  last_verified_at,
  last_seen_at,
  updated_at
) values
(
  'cheetos-crunchy-flamin-hot-cheese-flavored-snacks',
  'Crunchy Flamin'' Hot Cheese Flavored Snacks',
  'Cheetos Crunchy Flamin'' Hot',
  'Cheetos',
  'snacks',
  'cheese-snacks',
  array['hot cheetos','flamin hot cheetos','cheetos flamin hot','cheetos crunchy flamin hot','hot cheetos crunchy'],
  array['branded','packaged','grocery','snack','cheese snack','spicy','flamin hot'],
  array['028400329491'],
  'About 21 pieces (28 g)',
  28,
  160,
  1,
  15,
  11,
  null,
  0,
  210,
  28,
  'PepsiCo SmartLabel',
  'manufacturer_label',
  '028400329491',
  'https://smartlabel.pepsico.info/028400329491-0012-en-US/index.html',
  jsonb_build_object('manufacturer','Frito-Lay, Inc.','label_updated','2024-05-03'),
  true,
  0.99,
  95,
  false,
  true,
  now(),
  now(),
  now()
),
(
  'cheetos-puffs-flamin-hot-cheese-flavored-snacks',
  'Puffs Flamin'' Hot Cheese Flavored Snacks',
  'Cheetos Puffs Flamin'' Hot',
  'Cheetos',
  'snacks',
  'cheese-snacks',
  array['hot cheetos puffs','flamin hot cheetos puffs','cheetos flamin hot puffs','cheetos puffs flamin hot','hot cheetos puff'],
  array['branded','packaged','grocery','snack','cheese snack','spicy','flamin hot','puffs'],
  array['028400596695'],
  'About 13 pieces (28 g)',
  28,
  160,
  1,
  15,
  10,
  null,
  null,
  280,
  28,
  'PepsiCo SmartLabel',
  'manufacturer_label',
  '028400596695',
  'https://smartlabel.pepsico.info/028400596695-0015-en-US/index.html',
  jsonb_build_object('manufacturer','Frito-Lay, Inc.','label_updated','2026-02-07'),
  true,
  0.99,
  94,
  false,
  true,
  now(),
  now(),
  now()
)
on conflict (canonical_key) do update set
  name = excluded.name,
  display_name = excluded.display_name,
  brand = excluded.brand,
  category = excluded.category,
  subcategory = excluded.subcategory,
  aliases = excluded.aliases,
  tags = excluded.tags,
  upcs = excluded.upcs,
  serving_size = excluded.serving_size,
  serving_grams = excluded.serving_grams,
  calories = excluded.calories,
  protein_g = excluded.protein_g,
  carbs_g = excluded.carbs_g,
  fat_g = excluded.fat_g,
  fiber_g = excluded.fiber_g,
  sugar_g = excluded.sugar_g,
  sodium_mg = excluded.sodium_mg,
  nutrition_basis_grams = excluded.nutrition_basis_grams,
  source = excluded.source,
  source_type = excluded.source_type,
  source_id = excluded.source_id,
  source_url = excluded.source_url,
  source_payload = excluded.source_payload,
  verified = excluded.verified,
  confidence = excluded.confidence,
  popularity = excluded.popularity,
  retailer_private_label = excluded.retailer_private_label,
  active = excluded.active,
  last_verified_at = excluded.last_verified_at,
  last_seen_at = excluded.last_seen_at,
  updated_at = excluded.updated_at;
